# Generated by Django 2.2.2 on 2019-08-26 05:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_note_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 26, 5, 29, 42, 505167, tzinfo=utc)),
        ),
    ]
